ACTIVITY_TYPES = {
    0: 'Rock Climbing',
    1: 'Cruise',
    2: 'Fishing',
    3: 'Potluck',
    4: 'Board Game',
    5: 'Trivia',
    6: 'Improv Workshop',
    7: 'Karaoke Night',
    8: 'Go-Kart Racing',
    9: 'Volunteering',
    10: 'Watching Movie',
    11: 'Escape Room',
    12: 'Laser Tag',
    13: 'Murder Mystery',
    14: 'Kayaking',
    15: 'Trampoline',
    16: 'Canoeing',
    17: 'Painting Class',
    18: 'Cooking Class',
    19: 'Museum Tour',
    20: 'Sports Game',
    21: 'Picnic',
    22: 'Hiking',
    23: 'Hip-hop Class',
    24: 'Theater Show',
    25: 'Yoga',
    26: 'Happy Hour',
    27: 'Poker',
    28: 'Wine Tasting',
    29: 'Chess',
    30: 'Video Games',
    31: 'Arcade Games',
    32: 'Biking',
}